/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Cars;
import model.CarsCatalog;

/**
 *
 * @author krishna
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    CarsCatalog catalog;
    public ViewJPanel(CarsCatalog catalog ) {
        initComponents();
        this.catalog=catalog;

        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewCars = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCars = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtManufacturedBy = new javax.swing.JTextField();
        txtSerialNumber = new javax.swing.JTextField();
        txtSeats = new javax.swing.JTextField();
        lblModelNumber = new javax.swing.JLabel();
        lblManufacturedYear = new javax.swing.JLabel();
        txtManufacturedYear = new javax.swing.JTextField();
        lblMaintananceCertificate = new javax.swing.JLabel();
        lblSeats = new javax.swing.JLabel();
        chkMaintainanceCertificate = new javax.swing.JCheckBox();
        chkIsAvailable = new javax.swing.JCheckBox();
        txtModelNumber = new javax.swing.JTextField();
        lblGeoLocation = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtGeoLocation = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblIsAvailable = new javax.swing.JLabel();
        lblManufacturedBy = new javax.swing.JLabel();
        lblSerialNumber = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        txtLastUpdate = new javax.swing.JTextField();
        lbllastUpdate = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setPreferredSize(new java.awt.Dimension(904, 961));

        lblViewCars.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewCars.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewCars.setText("View Cars Details");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 700));

        tblCars.setBackground(new java.awt.Color(0, 255, 204));
        tblCars.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Manufactured by", "Manufactured date", "Serial no.", "Model no.", "Geolocation", "Seats", "Is Available", "Is certificate expired"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Byte.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCars.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblCars.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jScrollPane1.setViewportView(tblCars);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblModelNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblModelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblModelNumber.setText("Model number:");

        lblManufacturedYear.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblManufacturedYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturedYear.setText("Manufactured year:");

        lblMaintananceCertificate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblMaintananceCertificate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblMaintananceCertificate.setText("maintanance certificate expired:");

        lblSeats.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblSeats.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSeats.setText("Number of seats:");

        chkIsAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIsAvailableActionPerformed(evt);
            }
        });

        lblGeoLocation.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblGeoLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGeoLocation.setText("Geolocation:");

        lblName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblName.setText("Name:");

        txtGeoLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeoLocationActionPerformed(evt);
            }
        });

        lblIsAvailable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblIsAvailable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblIsAvailable.setText("Car Available:");

        lblManufacturedBy.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblManufacturedBy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblManufacturedBy.setText("Manufactured company:");

        lblSerialNumber.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblSerialNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSerialNumber.setText("Serial number:");

        btnUpdate.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnImport.setText("Import Data");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        lbllastUpdate.setText("Last Updated At:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbllastUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(btnImport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGeoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtGeoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(71, 71, 71)
                                        .addComponent(lblIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblMaintananceCertificate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkIsAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chkMaintainanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblManufacturedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtManufacturedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 334, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblViewCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(btnUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblViewCars, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImport)
                    .addComponent(lbllastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturedBy)
                    .addComponent(txtManufacturedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturedYear)
                    .addComponent(txtManufacturedYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSeats)
                    .addComponent(txtSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerialNumber)
                    .addComponent(txtSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelNumber)
                    .addComponent(txtModelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoLocation)
                    .addComponent(txtGeoLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkIsAvailable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIsAvailable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMaintananceCertificate)
                    .addComponent(chkMaintainanceCertificate, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addContainerGap(384, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
         // TODO add your handling code here:
         int selectedRowIndex=tblCars.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Select which row to delete");
         }
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        System.out.println(model.getValueAt(selectedRowIndex,0));
        Cars selectedCar=(Cars) model.getValueAt(selectedRowIndex,0);
                System.out.println(selectedCar);

        catalog.deleteCar(selectedCar);
        JOptionPane.showMessageDialog(this, "Selected Car entry deleted");
        populateTable();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    catalog.setLast_Updated(date);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void chkIsAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIsAvailableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkIsAvailableActionPerformed

    private void txtGeoLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeoLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeoLocationActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
         // TODO add your handling code here: 
         int selectedRowIndex=tblCars.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Please select a row to edit");
         }
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
//        Cars selectedCar=(Cars) model.getValueAt(selectedRowIndex,0);
        txtName.setText(String.valueOf(model.getValueAt(selectedRowIndex, 0)));
        txtManufacturedBy.setText(String.valueOf(model.getValueAt(selectedRowIndex, 1)));
        txtManufacturedYear.setText(String.valueOf(model.getValueAt(selectedRowIndex, 2)));
        txtGeoLocation.setText(String.valueOf(model.getValueAt(selectedRowIndex, 5)));
        txtModelNumber.setText(String.valueOf(model.getValueAt(selectedRowIndex, 4)));
        txtSerialNumber.setText(String.valueOf(model.getValueAt(selectedRowIndex, 3)));
        chkIsAvailable.setSelected(Boolean.valueOf(model.getValueAt(selectedRowIndex, 7).toString()));
        chkMaintainanceCertificate.setSelected(Boolean.valueOf(model.getValueAt(selectedRowIndex, 8).toString()));
        txtSeats.setText(String.valueOf(String.valueOf(model.getValueAt(selectedRowIndex, 6))));

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
          int selectedRowIndex=tblCars.getSelectedRow();
         if(selectedRowIndex<0){
             JOptionPane.showMessageDialog(this, "Please select a row to update");
         }
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        Cars selectedCar=(Cars) model.getValueAt(selectedRowIndex,0);
       selectedCar.setName(txtName.getText());
       selectedCar.setManufactured_by(txtManufacturedBy.getText());
       selectedCar.setManufactured_year(Integer.parseInt(txtManufacturedYear.getText()));
       selectedCar.setGeolocation(txtGeoLocation.getText());
       selectedCar.setSeats(Byte.parseByte(txtSeats.getText()));
       selectedCar.setSerial_number(txtSerialNumber.getText() );
       selectedCar.setModel_number(txtModelNumber.getText());
       selectedCar.setIsAvailable(chkIsAvailable.isSelected());
       selectedCar.setIs_maintanance_certificate_expired(chkMaintainanceCertificate.isSelected());
       JOptionPane.showMessageDialog(this, "Entry has been updated");
     SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    Date date = new Date();  
    catalog.setLast_Updated(date);
            txtLastUpdate.setText(formatter.format(catalog.getLast_Updated()));

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
                addDummyData();
    SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");  
    
    Date date = new Date();  
    catalog.setLast_Updated(date);
    txtLastUpdate.setText(formatter.format(catalog.getLast_Updated()));

    }//GEN-LAST:event_btnImportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkIsAvailable;
    private javax.swing.JCheckBox chkMaintainanceCertificate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblGeoLocation;
    private javax.swing.JLabel lblIsAvailable;
    private javax.swing.JLabel lblMaintananceCertificate;
    private javax.swing.JLabel lblManufacturedBy;
    private javax.swing.JLabel lblManufacturedYear;
    private javax.swing.JLabel lblModelNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSeats;
    private javax.swing.JLabel lblSerialNumber;
    private javax.swing.JLabel lblViewCars;
    private javax.swing.JLabel lbllastUpdate;
    private javax.swing.JTable tblCars;
    private javax.swing.JTextField txtGeoLocation;
    private javax.swing.JTextField txtLastUpdate;
    private javax.swing.JTextField txtManufacturedBy;
    private javax.swing.JTextField txtManufacturedYear;
    private javax.swing.JTextField txtModelNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSeats;
    private javax.swing.JTextField txtSerialNumber;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
        model.setRowCount(0);
        for(Cars car: catalog.getCatalog()){
        Object[] row=new Object[10];
        row[0]=car;
        row[1]=car.getManufactured_by();
        row[2]=car.getManufactured_year();
        row[3]=car.getSerial_number();
        row[4]=car.getModel_number();
        row[6]=car.getSeats();
        row[7]=car.isIsAvailable();
        row[8]=car.getIs_maintanance_certificate_expired();
        row[5]=car.getGeolocation();
//        row[5]=car.getName();
model.addRow(row);
        }
    }
     private void addDummyData() {
        
        String filePath="/Users/Soun/Documents/Untitled.txt";
        File file =new File(filePath);
//        try{
        try {
          FileReader fr = new FileReader(file);
         BufferedReader br=new BufferedReader(fr);
         DefaultTableModel model = (DefaultTableModel) tblCars.getModel();
         Object[] lines=br.lines().toArray();
         for(int i=0;i<lines.length;i++){
        Object[] row=lines[i].toString().split(" ");
              Cars car=catalog.addNewCar();
       car.setName(String.valueOf(row[0]));
       car.setManufactured_by(String.valueOf(row[1]));
       car.setManufactured_year(Integer.valueOf(row[2].toString()));
       car.setGeolocation(String.valueOf(row[5]));
       car.setSeats(Byte.valueOf(row[6].toString()));
       car.setSerial_number(String.valueOf(row[3]) );
       car.setModel_number(String.valueOf(row[4]));
       car.setIsAvailable(Boolean.valueOf(row[7].toString()));
       car.setIs_maintanance_certificate_expired(Boolean.valueOf(row[8].toString()));
        model.addRow(row); 
         }        

     }
        catch (FileNotFoundException ex) {
            Logger.getLogger(ViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
}
